api_platform:
    title: Audiodescription Patrimony API
    show_webby: false
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_enabled: true
        pagination_client_items_per_page: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: itemsPerPage # Default value
