parameters:
  patrimony_api_key: '%env(PATRIMONY_API_KEY)%'
  webedia_api_platform.auth_endpoint: '%env(WEBEDIA_API_PLATFORM_AUTH_ENDPOINT)%'
  webedia_api_platform.client_id: '%env(WEBEDIA_API_PLATFORM_CLIENT_ID)%'
  webedia_api_platform.client_secret: '%env(WEBEDIA_API_PLATFORM_CLIENT_SECRET)%'
  webedia_api_platform.audience: '%env(WEBEDIA_API_PLATFORM_AUDIENCE)%'
  webedia_api_platform.root_url: '%env(WEBEDIA_API_PLATFORM_ROOT_URL)%'
  oidc_ad.base_url: '%env(OIDC_AD_BASE_URL)%'
  oidc_ad.public_url: '%env(OIDC_AD_PUBLIC_URL)%'
  oidc_ad.client_id: '%env(OIDC_AD_CLIENT_ID)%'
  oidc_ad.client_secret: '%env(OIDC_AD_CLIENT_SECRET)%'
  oidc_ad.redirect_base_url: '%env(OIDC_AD_REDIRECT_BASE_URL)%'
  oidc_ad.public_key: '%env(OIDC_AD_PUBLIC_KEY)%'
  canal_vod.api.url: '%env(CANAL_VOD_API_URL)%'
  canal_replay.api.url: '%env(CANAL_REPLAY_API_URL)%'
  canal_vod.api.auth_token: '%env(CANAL_VOD_API_AUTH_TOKEN)%'
  arte_tv.api.url: '%env(ARTE_TV_API_URL)%'
  orange_vod.filename: '%env(ORANGE_VOD_FILENAME)%'
  france_tv.filename: '%env(FRANCE_TV_FILENAME)%'
  lacinetek.api.url: '%env(LACINETEK_API_URL)%'
  lacinetek.api.auth_token: '%env(LACINETEK_API_AUTH_TOKEN)%'
  tf1.api.user: '%env(TF1_API_USER)%'
  tf1.api.password: '%env(TF1_API_PASSWORD)%'
  tf1.api.url: '%env(TF1_API_URL)%'
