services:
  nginx:
    image: nginx:latest
    ports:
      - "8097:80"
    volumes:
      - ./drupal:/var/www/html
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - drupal-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiodescription.rule=Host(`audiodescription.corfm.at`, `audiodescription.incubateur.net`)"
      - "traefik.http.routers.audiodescription.entrypoints=websecure"

  php:
    build:
      context: .
      dockerfile: docker/prod/php/Dockerfile
    volumes:
      - ./drupal:/var/www/html
      - ./docker/prod/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - drupal-network

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - drupal-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    deploy:
      resources:
        limits:
          memory: 1500M
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - drupal-network

volumes:
  db-data:
  elastic-data:

networks:
  drupal-network:
  web:
    external: true