services:
  drupal:
    build:
      context: .
      dockerfile: docker/drupal/dev/php/Dockerfile
    ports:
      - 8080:80
    working_dir: /app/public/drupal
    environment:
      S3_ACCESS_KEY: 'S3KEY'
      S3_SECRET_KEY: 'S3SECRET'
      S3_ENDPOINT: 'http://s3:9000'
      S3_BUCKET: 'audiodescription'
      S3_REGION: 'us-east-1'
      S3_HOSTNAME: 's3:9000'
      S3_DOMAIN: 'localhost:9000'
      S3_USE_FOR_MAIN_STORAGE: 'TRUE'
      S3_USE_FOR_PUBLIC: 'TRUE'
      S3_USE_FOR_PRIVATE: 'TRUE'
      S3_USE_CUSTOM_HOST: 'TRUE'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    volumes:
      - .:/app/public
      - ./docker/drupal/dev/caddy/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/drupal/dev/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - s3
      - redis
    networks:
      - ad-network

  patrimony:
    build:
      context: .
      dockerfile: ./docker/patrimony/dev/php/Dockerfile
    restart: always
    working_dir: /app/public/patrimony
    ports:
      - 8083:80
    environment:
      GRUMPHP_PROJECT_DIR: '/app/public/patrimony'
      GRUMPHP_COMPOSER_DIR: '/app/public/patrimony'
      GRUMPHP_GIT_REPOSITORY_DIR: '/app/public/.git'
      GRUMPHP_GIT_WORKING_DIR: '/app/public'
    volumes:
      - .:/app/public
      - ./docker/patrimony/dev/caddy/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/patrimony/dev/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ad-network

  db:
    image: postgres:16-bookworm
    command: -c 'max_connections=10'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init-patrimony-db.sh:/docker-entrypoint-initdb.d/init-patrimony-db.sh
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=audiodescription
      - POSTGRES_PASSWORD=audiodescription
    ports:
      - '5432:5432'
    networks:
      - ad-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./drupal/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - ad-network

  s3:
    build:
      context: ./
      dockerfile: ./docker/s3/Dockerfile
    entrypoint: /bin/sh /usr/local/bin/entrypoint.sh
    volumes:
      - s3:/data
      - ./docker/s3/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      RUSTFS_ACCESS_KEY: 'S3KEY'
      RUSTFS_SECRET_KEY: 'S3SECRET'
      DEFAULT_BUCKETS: 'audiodescription:public'
    ports:
      - '9001:9001'
      - '9000:9000'
    networks:
      - ad-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - ad-network

  node:
    image: node:20
    volumes:
      - ./drupal/web/themes/ad_theme:/usr/app
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"

  a11y:
    image: node:20
    volumes:
      - ./:/usr/app
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"

volumes:
  db-data:
  s3:

networks:
  ad-network: