services:
  patrimony:
    build:
      context: .
      dockerfile: ./docker/patrimony/prod/php/Dockerfile
    restart: always
    working_dir: /app/public/patrimony
    ports:
      - 8081:80
    volumes:
      - .:/app/public
      - ./docker/patrimony/prod/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/patrimony/prod/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ad-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiodescription_patrimony.rule=Host(`patrimony.audiodescription.beta.gouv.fr`)"
      - "traefik.http.routers.audiodescription_patrimony.entrypoints=websecure"
      - "traefik.http.routers.audiodescription_patrimony.middlewares=strip-www"

  drupal:
    restart: always
    build:
      context: .
      dockerfile: docker/drupal/prod/php/Dockerfile
    ports:
      - 8080:80
    working_dir: /app/public/drupal
    volumes:
      - .:/app/public
      - ./docker/drupal/prod/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/drupal/prod/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - ad-network
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiodescription.rule=Host(`audiodescription.beta.gouv.fr`) || Host(`www.audiodescription.beta.gouv.fr`)"
      - "traefik.http.routers.audiodescription.entrypoints=websecure"
      - "traefik.http.routers.audiodescription.middlewares=strip-www"

  db:
    image: postgres:17-bookworm
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init-patrimony-db.sh:/docker-entrypoint-initdb.d/init-patrimony-db.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - ad-network

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - ad-network

volumes:
  db-data:
  elastic-data:

networks:
  ad-network:
  web:
    external: true
