<?php

/**
 * Implements hook_theme().
 */
function audiodescription_theme($existing, $type, $theme, $path)
{
  return [
    'homepage' => [
      'render element' => 'children',
      'template' => 'homepage',
      'path' => $path . '/templates',
      'variables' => [
        'header' => null,
        'infos' => null,
        'about' => null,
        'highlighted_collections' => null,
        'collections' => null,
      ],
    ],
    'hp_highlighted_collections_block' => [
      'render element' => 'children',
      'template' => 'hp-highlighted-collections-block',
      'path' => $path . '/templates',
      'variables' => [
        'collections' => null,
      ],
    ],
    'hp_collections_block' => [
      'render element' => 'children',
      'template' => 'hp-collections-block',
      'path' => $path . '/templates',
      'variables' => [
        'collections' => null,
        'collection_genres' => null,
        'title' => null
      ],
    ],
  ];

}
