<?php

/**
 * @file
 * Contains audiodescription module-related hooks.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function audiodescription_theme($existing, $type, $theme, $path) {
  return [
    'homepage' => [
      'render element' => 'children',
      'template' => 'homepage',
      'path' => $path . '/templates',
      'variables' => [
        'header' => NULL,
        'infos' => NULL,
        'about' => NULL,
        'highlighted_collections' => NULL,
        'collections' => NULL,
        'search_form' => NULL,
        'last_movies' => NULL,
      ],
    ],
    'hp_highlighted_collections_block' => [
      'render element' => 'children',
      'template' => 'hp-highlighted-collections-block',
      'path' => $path . '/templates',
      'variables' => [
        'collections' => NULL,
      ],
    ],
    'hp_collections_block' => [
      'render element' => 'children',
      'template' => 'hp-collections-block',
      'path' => $path . '/templates',
      'variables' => [
        'collections' => NULL,
        'collection_genres' => NULL,
        'title' => NULL,
      ],
    ],
    'hp_last_movies_block' => [
      'render element' => 'children',
      'template' => 'hp-last-movies-block',
      'path' => $path . '/templates',
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'cta' => NULL,
        'movies' => NULL,
      ],
    ],
    'movies_contact_block' => [
      'render element' => 'children',
      'template' => 'movies-contact-block',
      'path' => $path . '/templates',
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'email' => NULL,
      ],
    ],
    'search_contact_block' => [
      'render element' => 'children',
      'template' => 'search-contact-block',
      'path' => $path . '/templates',
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'cta' => NULL,
      ],
    ],
    'movie_search' => [
      'render element' => 'children',
      'template' => 'movie-search',
      'path' => $path . '/templates',
      'variables' => [
        'movies' => NULL,
        'form' => NULL,
        'filtersForm' => NULL,
      ],
    ],
    'header_search_form_block' => [
      'render element' => 'children',
      'template' => 'header-search-form-block',
      'path' => $path . '/templates',
      'variables' => [
        'form' => NULL,
      ],
    ],
    'error_403' => [
      'render element' => 'children',
      'template' => 'error-403',
      'path' => $path . '/templates',
    ],
    'error_404' => [
      'render element' => 'children',
      'template' => 'error-404',
      'path' => $path . '/templates',
    ],

    'back_to_top_block' => [
      'variables' => [
        'custom_data' => [],
        'custom_string' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_node_presave().
 */
function audiodescription_node_presave(Node $node) {
  $pathauto_service = \Drupal::service('pathauto.alias_cleaner');

  if ($node->getType() === 'movie') {
    $title = $node->getTitle();
    $clean_title = $pathauto_service->cleanString($title);
    $node->set('field_clean_title', $clean_title);
  }
}

/**
 * Implémentation de hook_block_view_alter().
 */
function audiodescription_block_view_alter(array &$build, BlockPluginInterface $block) {

  $current_route = \Drupal::routeMatch()->getRouteName();

  $routes = [
    'audiodescription.error.403',
    'audiodescription.error.404',
  ];

  if (in_array($current_route, $routes)) {
    $blocks = [
      'system_breadcrumb_block',
      'page_title_block',
      'back_to_top_block',
    ];

    if (in_array($block->getBaseId(), $blocks)) {
      $build = [];
    }
  }
}
